In Decision Trees, CART stands for Classification and Regression Trees. It is a popular algorithm introduced by Breiman et al. for building decision trees.

Key Features of CART
Supports both Classification and Regression
Classification Tree: Predicts categorical outcomes (e.g., Yes/No, Spam/Not Spam).
Regression Tree: Predicts continuous values (e.g., house price, temperature).
Binary Splits
Every internal node splits into exactly two branches.

Example:

Age < 30?
   /     \
 Yes     No
Splitting Criteria

For classification, CART typically uses Gini Impurity.

Gini=1−∑p
i
2
	​


where p
i
	​

 is the probability of class i.

For regression, CART uses measures like Mean Squared Error (MSE) or variance reduction.
Tree Pruning
CART grows a large tree and then prunes it to avoid overfitting.
Uses cost-complexity pruning to find the optimal tree size.
Example (Classification)

Suppose we want to predict whether a student will pass:

Study Hours	Pass
2	No
3	No
5	Yes
6	Yes

CART may create:

Study Hours < 4?
      /      \
    No       Yes
Advantages

✔ Easy to understand and visualize
✔ Handles numerical and categorical data
✔ Requires little data preprocessing
✔ Can model non-linear relationships

Disadvantages

✘ Can overfit if not pruned
✘ Sensitive to small changes in data
✘ Single trees may have lower accuracy than ensemble methods like Random Forest

Entropy and Information Gain in Decision Trees
1. Entropy

Entropy measures the impurity or uncertainty in a dataset.

Formula:

Entropy(S)=−
i=1
∑
n
	​

p
i
	​

log
2
	​

(p
i
	​

)

where:

p
i
	​

 = probability of class i
S = dataset

Interpretation:

Entropy = 0 → Pure dataset (all samples belong to one class)
Entropy = 1 → Maximum uncertainty (for two classes with equal probability)
Example

Suppose a dataset has:

6 Yes
4 No
p(Yes)=
10
6
	​

=0.6,p(No)=
10
4
	​

=0.4
Entropy(S)=−(0.6log
2
	​

0.6+0.4log
2
	​

0.4)
Entropy(S)≈0.971
2. Information Gain

Information Gain (IG) measures how much uncertainty is reduced after splitting the dataset on an attribute.

Formula:

IG(S,A)=Entropy(S)−
v∈Values(A)
∑
	​

∣S∣
∣S
v
	​

∣
	​

Entropy(S
v
	​

)

where:

S = original dataset
A = attribute used for splitting
S
v
	​

 = subset after the split

Decision Tree Rule:

Calculate IG for each attribute.
Choose the attribute with the highest Information Gain as the splitting node.
Simple Example

Dataset:

Weather	Play
Sunny	No
Sunny	No
Rainy	Yes
Rainy	Yes

Initial entropy:

Entropy(S)=1

Split on Weather:

Sunny subset → all No → Entropy = 0
Rainy subset → all Yes → Entropy = 0

Weighted entropy after split:

0

Information Gain:

IG=1−0=1

Since IG is maximum, Weather is an excellent attribute for splitting.

Quick Difference
Entropy	Information Gain
Measures impurity/disorder	Measures reduction in impurity
Calculated for a dataset	Calculated for an attribute
Lower is better	Higher is better
Used to quantify uncertainty	Used to choose the best split

Model Evaluation Techniques in Machine Learning

Model evaluation techniques are used to measure how well a machine learning model performs on unseen data.

1. Train-Test Split
Dataset is divided into two parts:
Training Set (e.g., 80%)
Testing Set (e.g., 20%)
Model is trained on the training set and evaluated on the test set.

Advantages:

Simple and fast.

Disadvantages:

Performance depends on how data is split.
2. Cross-Validation
k-Fold Cross-Validation
Dataset is divided into k equal folds.
Model is trained on k−1 folds and tested on the remaining fold.
Process repeats k times.
Final score = Average of all scores.

Example (5-Fold):

Fold1 → Test, Fold2-5 → Train
Fold2 → Test, Fold1,3,4,5 → Train
...

Advantages:

More reliable than train-test split.
Uses all data for training and testing.
3. Leave-One-Out Cross-Validation (LOOCV)

Special case of k-fold where:

k=n

(n = number of observations)

One sample is used for testing and the rest for training.

Advantage: Uses maximum data for training.

Disadvantage: Computationally expensive.

4. Stratified Cross-Validation
Maintains the same class distribution in each fold as in the original dataset.
Useful for imbalanced datasets.
5. Bootstrap Method
Random sampling with replacement.
Some samples may appear multiple times.
Used when dataset is small.
Evaluation Metrics
For Classification
Accuracy
Accuracy=
TP+TN+FP+FN
TP+TN
	​

Precision
Precision=
TP+FP
TP
	​

Recall
Recall=
TP+FN
TP
	​

F1-Score
F1=2×
Precision+Recall
Precision×Recall
	​

Confusion Matrix
Actual / Predicted	Positive	Negative
Positive	TP	FN
Negative	FP	TN
For Regression
Mean Absolute Error (MAE)
MAE=
n
1
	​

∑∣y
i
	​

−
y
^
	​

i
	​

∣
Mean Squared Error (MSE)
MSE=
n
1
	​

∑(y
i
	​

−
y
^
	​

i
	​

)
2
Root Mean Squared Error (RMSE)
RMSE=
MSE
	​

R-Squared (R
2
)
R
2
=1−
SS
tot
	​

SS
res
	​

	​

In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVC,SVR

In [2]:
df=pd.read_csv(r'D:\Data Science with AI & ML\SITP-12th-May\MACHINE LEARNING\PROJECT 3\DATA\clean_loan_data.csv')

In [3]:
df

,Unnamed: 0,name,income,credit_score,loan_amount,years_employed,loan_approved
0,0,0,113810,389,39698,27,1
1,1,1,44592,729,15446,28,1
2,2,2,33278,584,11189,13,1
3,3,3,127196,344,48823,29,1
4,4,4,66048,496,47174,4,1
...,...,...,...,...,...,...,...
1995,1995,1995,92163,770,12251,13,2
1996,1996,1996,38799,635,48259,17,1
1997,1997,1997,41957,763,16752,5,2
1998,1998,1998,139022,360,24031,35,1
1999,1999,1999,41188,482,31397,6,1

In [4]:
df.drop(["Unnamed: 0", "name"], axis=1, inplace=True)

In [5]:
x=df.drop("loan_approved", axis=1)

In [6]:
y=df[['loan_approved']]

In [7]:
x

      income  credit_score  loan_amount  years_employed
0     113810           389        39698              27
1      44592           729        15446              28
2      33278           584        11189              13
3     127196           344        48823              29
4      66048           496        47174               4
...      ...           ...          ...             ...
1995   92163           770        12251              13
1996   38799           635        48259              17
1997   41957           763        16752               5
1998  139022           360        24031              35
1999   41188           482        31397               6

[2000 rows x 4 columns]

In [8]:
y

      loan_approved
0                 1
1                 1
2                 1
3                 1
4                 1
...             ...
1995              2
1996              1
1997              2
1998              1
1999              1

[2000 rows x 1 columns]

In [9]:
y['loan_approved'].unique()

array([1, 2])

In [10]:
y['loan_approved'].value_counts()

loan_approved
1    1121
2     879
Name: count, dtype: int64

In [11]:
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42
)
x_train.shape, y_train.shape, x_test.shape, y_test.shape

((1600, 4), (1600, 1), (400, 4), (400, 1))

In [12]:
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
dtc=DecisionTreeClassifier(criterion='entropy')

In [13]:
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [14]:
y_pred =dtc.predict(x_test)

In [15]:
dtc.predict([[130290,  447,  16496,  10]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [16]:
print(dtc.score(x_train, y_train))
print(dtc.score(x_test, y_test))

1.0
0.9625

In [17]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'entropy',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [18]:
# sv=LinearRegression()
# sv.fit(x_train, y_train)

In [19]:
from sklearn.ensemble import RandomForestRegressor
sv=RandomForestRegressor()
sv.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestRegressor()

In [20]:
print(sv.score(x_train, y_train))
print(sv.score(x_test, y_test))

0.9900401790255314
0.9070554758127471

In [21]:
print(x_train.shape)
print(y_train.shape)

(1600, 4)
(1600, 1)

In [22]:
import joblib
joblib.dump(sv, "model_rfr.lb")

['model_rfr.lb']

In [23]:
model=joblib.load('model_rfr.lb')

In [24]:
model.predict([[44592,  729,  15446,  28]])

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(

array([1.08])

In [25]:
sv=SVC()
sv.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVC()

In [26]:
print(sv.score(x_train, y_train))
print(sv.score(x_test, y_test))

0.63
0.5975

In [27]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test, y_pred)

array([[211,   6],
       [  9, 174]])

In [28]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.96      0.97      0.97       217
           2       0.97      0.95      0.96       183

    accuracy                           0.96       400
   macro avg       0.96      0.96      0.96       400
weighted avg       0.96      0.96      0.96       400

In [29]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB,MultinomialNB

In [30]:
bnb=BernoulliNB()
bnb.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\utils\validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

BernoulliNB()

In [31]:
import pandas as pd
y=pd.DataFrame(y)

In [32]:
y.value_counts

<bound method DataFrame.value_counts of       loan_approved
0                 1
1                 1
2                 1
3                 1
4                 1
...             ...
1995              2
1996              1
1997              2
1998              1
1999              1

[2000 rows x 1 columns]>

In [33]:
bnb.score(x_train, y_train)

0.565

In [34]:
bnb.score(x_test, y_test)

0.5425

In [35]:
bnb.predict(x_test)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1])

In [36]:
y_test

      loan_approved
1860              1
353               2
1333              2
905               2
1289              2
...             ...
965               1
1284              1
1739              2
261               2
535               2

[400 rows x 1 columns]

In [37]:
# #  MSE
# from sklearn.metrics import mean_squared_error as mse
# mse(y_test, y_pred)

In [38]:
# from sklearn.datasets import fetch_california_housing

In [39]:
# x, y =fetch_california_housing(return_X_y=True)

In [40]:
# x

In [41]:
# y

In [42]:
# x_train, x_test, y_train, y_test = train_test_split(
#     x, y,
#     test_size=0.2,
#     random_state=42
# )
# x_train.shape, y_train.shape, x_test.shape, y_test.shape

In [43]:
# from sklearn.tree import DecisionTreeRegressor
# dtr=DecisionTreeRegressor()
# dtr.fit(x_train, y_train)

In [44]:
# dtr.score(x_train, y_train)

In [45]:
# dtr.score(x_test, y_test)

In [46]:
# y_pred=dtr.predict(x_test)

In [47]:
# y_pred

In [48]:
# # MSE & MAE
# from sklearn.metrics import mean_absolute_error, mean_squared_error
# print("Mean_squared_error:-",mean_squared_error(y_test, y_pred))
# print("Mean_absolute_error:-",mean_absolute_error(y_test, y_pred))

In [49]:
# rmse=np.sqrt(mean_squared_error(y_test, y_pred))

In [50]:
# rmse

In [51]:
# rmse=np.sqrt(mean_absolute_error(y_test, y_pred))

In [52]:
# rmse

In [53]:
# from sklearn.datasets import load_breast_cancer
# data = load_breast_cancer()
# x = data.data
# y = data.target
# print(x.shape)
# print(y.shape)

In [54]:
# x

In [55]:
# y

In [56]:
# from sklearn.model_selection import train_test_split

In [57]:
# x_train, x_test, y_train, y_test = train_test_split(
#     x, y,
#     test_size=0.2,
#     random_state=42
# )
# x_train.shape, y_train.shape, x_test.shape, y_test.shape

In [58]:
from sklearn.neighbors import KNeighborsClassifier
knn =KNeighborsClassifier()
knn.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neighbors\_classification.py:243: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

KNeighborsClassifier()

In [59]:
pred =knn.predict(x_test)

In [60]:
pred

array([1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 2,
       1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 2, 1, 1, 1,
       2, 2, 1, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2,
       1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 2, 1, 2,
       1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 1, 1,
       1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 2, 2, 2, 2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2,
       1, 1, 2, 1, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2,
       2, 2, 1, 2, 1, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 1, 1, 1, 2,
       1, 2, 1, 2, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
       2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2,
       1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1,
       2, 2, 2, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 2, 1,
       2, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 2,
       1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1,
       2, 2, 1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 2, 1,
       1, 2, 2, 1])

In [61]:
y_test

      loan_approved
1860              1
353               2
1333              2
905               2
1289              2
...             ...
965               1
1284              1
1739              2
261               2
535               2

[400 rows x 1 columns]

In [62]:
knn.score(x_test, y_test)

0.57

In [63]:
knn.score(x_train, y_train)

0.74

In [64]:
# without hyper parameter
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier()
rfc.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [65]:
rfc.fit(x_train, y_train)

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

RandomForestClassifier()

In [66]:
print(rfc.score(x_test, y_test))
print(rfc.score(x_train, y_train))

0.98
1.0

In [67]:
# With hyper paramter
from sklearn.ensemble import RandomForestClassifier
rfc =RandomForestClassifier(n_estimators=150, criterion='entropy', max_depth=1, min_samples_split=2)
rfc.fit(x_train, y_train)
print(rfc.score(x_test, y_test))
print(rfc.score(x_train, y_train))

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:1403: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

0.8625
0.87875

In [68]:
! pip install tensorflow

Requirement already satisfied: tensorflow in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (2.21.0)
Requirement already satisfied: absl-py>=1.0.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=25.9.23 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from tensorflow) (26.2)
Requirement already satisfied: protobuf<8.0.0,>=6.31.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (7.35.1)
Requirement already satisfied: requests<3,>=2.21.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (2.34.2)
Requirement already satisfied: setuptools in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (2.2.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (1.81.1)
Requirement already satisfied: keras>=3.12.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (3.14.1)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (2.4.6)
Requirement already satisfied: h5py<3.15.0,>=3.11.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (3.14.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.6.17)
Requirement already satisfied: wheel<1.0,>=0.23.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from keras>=3.12.0->tensorflow) (15.0.0)
Requirement already satisfied: namex in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from keras>=3.12.0->tensorflow) (0.19.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from rich->keras>=3.12.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\LENOVO\AppData\Roaming\Python\Python311\site-packages (from rich->keras>=3.12.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.12.0->tensorflow) (0.1.2)

In [69]:
import tensorflow as tf
print(tf.__version__)

2.21.0

In [70]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
print("TensorFlow Working Fine")

TensorFlow Working Fine

In [71]:
input_dim=x_train.shape[1]

In [72]:
model=Sequential()
model.add(Dense(units=64, activation='relu', input_dim=input_dim))
model.add(Dense(units=32,activation='relu'))
model.add(Dense(units=16,activation='relu'))

model.add(Dense(units=1, activation="linear"))

c:\Users\LENOVO\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [73]:
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [74]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
model.fit(x_train, y_train, epochs=10,batch_size=32)

Epoch 1/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - loss: 244834.2188 - mae: 289.8112
Epoch 2/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 2286.4834 - mae: 37.6162
Epoch 3/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 948.5160 - mae: 24.9204
Epoch 4/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 718.5615 - mae: 21.1122
Epoch 5/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 533.7291 - mae: 18.3586
Epoch 6/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 504.4176 - mae: 17.7922
Epoch 7/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 477.4202 - mae: 17.4460
Epoch 8/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 400.1473 - mae: 15.6045
Epoch 9/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 458.2779 - mae: 16.9581
Epoch 10/10
50/50 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 592.4582 - mae: 19.3848

In [76]:
model.predict(x_test)

13/13 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

array([[-38.59754   ],
       [-21.56385   ],
       [-10.246957  ],
       [-15.841928  ],
       [-40.65638   ],
       [-27.703499  ],
       [ -6.5438313 ],
       [-18.908089  ],
       [-16.929329  ],
       [-28.528694  ],
       [-31.124886  ],
       [-34.04725   ],
       [-47.63465   ],
       [-21.430061  ],
       [-12.945931  ],
       [-19.495491  ],
       [ -7.4940267 ],
       [ 11.727164  ],
       [-12.195931  ],
       [ 11.815055  ],
       [-23.239632  ],
       [  1.5670084 ],
       [-18.119026  ],
       [-12.307992  ],
       [-21.863167  ],
       [-15.319711  ],
       [ -5.204476  ],
       [ 31.511345  ],
       [-33.999397  ],
       [  3.1988444 ],
       [  1.0911783 ],
       [-27.359749  ],
       [-16.831184  ],
       [-36.06434   ],
       [-23.607063  ],
       [-23.859016  ],
       [ -9.730355  ],
       [-26.374275  ],
       [-19.376595  ],
       [ 23.941032  ],
       [ -5.5150228 ],
       [-24.902473  ],
       [ 21.661491  ],
       [-13.563363  ],
       [-54.757698  ],
       [-19.567757  ],
       [  8.770865  ],
       [-14.521127  ],
       [ 24.128044  ],
       [-25.94178   ],
       [-30.168343  ],
       [-29.997444  ],
       [ -4.708382  ],
       [ -1.1942221 ],
       [-20.456917  ],
       [ -6.432503  ],
       [-17.675667  ],
       [ -8.413461  ],
       [ -5.8563313 ],
       [ 15.286246  ],
       [-13.23182   ],
       [ 24.262321  ],
       [-37.073616  ],
       [-30.228401  ],
       [ -1.1729819 ],
       [ 10.092399  ],
       [ -1.0833822 ],
       [-35.354378  ],
       [-15.017465  ],
       [-23.958138  ],
       [ 15.429313  ],
       [-15.167611  ],
       [-16.34217   ],
       [-19.616096  ],
       [-46.96595   ],
       [ 13.009147  ],
       [-13.743539  ],
       [-11.187875  ],
       [ 14.553336  ],
       [-21.792244  ],
       [ 13.960563  ],
       [-34.40809   ],
       [-22.687141  ],
       [-20.451302  ],
       [ -9.129281  ],
       [-20.591194  ],
       [-31.930061  ],
       [-18.278206  ],
       [ -5.5960774 ],
       [-37.67518   ],
       [ -5.188851  ],
       [-19.063362  ],
       [-37.168343  ],
       [-50.312508  ],
       [-22.913948  ],
       [-26.908089  ],
       [-25.778938  ],
       [-31.834846  ],
       [-37.647346  ],
       [-16.104866  ],
       [  2.640739  ],
       [-44.53016   ],
       [ -7.442757  ],
       [-11.318246  ],
       [-29.394417  ],
       [-10.506234  ],
       [ 29.390251  ],
       [ -4.7852864 ],
       [-17.394905  ],
       [-13.323617  ],
       [ -6.5374837 ],
       [ -0.6275717 ],
       [  2.5587077 ],
       [ -8.669076  ],
       [ 22.223259  ],
       [-16.482796  ],
       [ -0.49744475],
       [ -2.1453938 ],
       [-10.940316  ],
       [  2.9122233 ],
       [ -5.9867024 ],
       [-26.803596  ],
       [  7.676872  ],
       [-10.332406  ],
       [ -8.716683  ],
       [-29.851448  ],
       [  8.221305  ],
       [ -1.8216635 ],
       [-22.42701   ],
       [-13.9876795 ],
       [-17.768929  ],
       [-16.335823  ],
       [ 11.669059  ],
       [-19.575325  ],
       [-27.259163  ],
       [ 28.937614  ],
       [-15.666879  ],
       [-20.179573  ],
       [  1.592399  ],
       [-23.347786  ],
       [-13.59974   ],
       [-21.047737  ],
       [ 27.678337  ],
       [ 15.026969  ],
       [ -3.571175  ],
       [-51.085335  ],
       [-29.391975  ],
       [-14.308724  ],
       [ -9.450082  ],
       [  1.9131998 ],
       [ 38.00158   ],
       [ -3.0096517 ],
       [-18.971321  ],
       [-21.380013  ],
       [-17.664192  ],
       [-25.688362  ],
       [  8.328727  ],
       [-28.578987  ],
       [ -1.0301596 ],
       [ 28.289177  ],
       [  2.6500163 ],
       [-27.479866  ],
       [-23.968636  ],
       [-16.696175  ],
       [ -4.1532063 ],
       [-19.423714  ],
       [ 24.458122  ],
       [-42.4076    ],
       [-10.958627  ],
       [-28.480843  ],
       [-38.985237  ],
       [-33.484993  ],
       [-14.579476  ],
       [-15.1751795 ],
       [-15.802865  ],
       [ 15.772086  ],
       [-29.069221  ],
       [-17.678596  ],
       [ 22.182     ],
       [-23.175179  ],
       [-14.673226  ],
       [-30.38807   ],
       [-18.39051   ],
       [-31.95057   ],
       [-39.392952  ],
       [-14.953988  ],
       [-25.290413  ],
       [-26.318733  ],
       [-18.271614  ],
       [-38.733284  ],
       [-12.041146  ],
       [-18.327522  ],
       [-33.649788  ],
       [-28.157112  ],
       [  0.84923494],
       [ -9.229501  ],
       [ -1.8216635 ],
       [-17.819466  ],
       [ -1.7576987 ],
       [ -3.6576009 ],
       [-31.85926   ],
       [-19.620003  ],
       [  1.7759928 ],
       [-27.522835  ],
       [-49.925667  ],
       [-30.853401  ],
       [-55.82557   ],
       [-29.625862  ],
       [  3.4610515 ],
       [-26.905647  ],
       [-17.41761   ],
       [  1.2476724 ],
       [ -2.76014   ],
       [-28.416878  ],
       [-16.148567  ],
       [-28.040901  ],
       [ -5.921517  ],
       [ 13.696158  ],
       [-37.026253  ],
       [ 11.3126135 ],
       [-11.494271  ],
       [-22.996956  ],
       [  0.23058261],
       [-18.559212  ],
       [-19.271858  ],
       [ -9.840707  ],
       [ -3.093636  ],
       [ 30.877068  ],
       [  7.2735515 ],
       [-18.331429  ],
       [  1.7564615 ],
       [-20.91639   ],
       [-21.516243  ],
       [ 11.613395  ],
       [-24.043343  ],
       [-42.94227   ],
       [ -3.1170735 ],
       [-27.607796  ],
       [-20.410774  ],
       [ 15.776481  ],
       [ -1.6351401 ],
       [  6.7115397 ],
       [-19.969612  ],
       [-15.245004  ],
       [-16.169807  ],
       [-16.001839  ],
       [-29.7743    ],
       [  4.0391765 ],
       [-31.671272  ],
       [  2.7755046 ],
       [-25.476448  ],
       [-13.238168  ],
       [ -4.2528157 ],
       [ -6.43348   ],
       [-31.965706  ],
       [-41.863167  ],
       [-13.523324  ],
       [-43.840706  ],
       [-12.722299  ],
       [-38.190315  ],
       [-11.773812  ],
       [-25.880745  ],
       [  0.06993808],
       [-30.556038  ],
       [-32.547737  ],
       [  2.595573  ],
       [-28.539192  ],
       [-13.6439295 ],
       [ -9.121957  ],
       [ 18.747673  ],
       [-27.520393  ],
       [-23.48719   ],
       [-21.161995  ],
       [ -0.5975424 ],
       [ -0.67835295],
       [-24.16468   ],
       [-29.201057  ],
       [-19.750862  ],
       [-29.187874  ],
       [ 19.428825  ],
       [-33.608284  ],
       [-49.812874  ],
       [-25.75428   ],
       [-44.289803  ],
       [-30.39051   ],
       [ 34.034294  ],
       [ -7.27723   ],
       [-12.785287  ],
       [-34.736214  ],
       [-36.709846  ],
       [-29.9618    ],
       [-25.101936  ],
       [-14.679574  ],
       [  2.8077312 ],
       [ -9.2359705 ],
       [-33.22596   ],
       [ -2.0719075 ],
       [-20.93055   ],
       [-32.366585  ],
       [ -3.9642415 ],
       [-15.40101   ],
       [-24.692513  ],
       [-26.152718  ],
       [-22.47718   ],
       [-11.623422  ],
       [  9.617301  ],
       [ -5.6827474 ],
       [-13.422738  ],
       [ 26.670036  ],
       [-25.092659  ],
       [-24.507454  ],
       [-36.08204   ],
       [-26.232307  ],
       [-23.109749  ],
       [ -7.457894  ],
       [-31.85633   ],
       [-26.446907  ],
       [  3.1588054 ],
       [  8.451285  ],
       [ -5.254769  ],
       [ -5.1102376 ],
       [-30.227913  ],
       [ -9.548348  ],
       [ 20.355095  ],
       [-22.25013   ],
       [ 10.995719  ],
       [-38.162483  ],
       [  5.4815593 ],
       [  6.411247  ],
       [-11.348763  ],
       [-23.599983  ],
       [-10.873178  ],
       [-17.064827  ],
       [ 10.5904455 ],
       [-19.759163  ],
       [-14.567025  ],
       [-23.584602  ],
       [-23.074104  ],
       [ -4.2315755 ],
       [-15.655404  ],
       [-37.195686  ],
       [-29.818245  ],
       [-13.105966  ],
       [-24.07557   ],
       [  1.4295572 ],
       [-10.814828  ],
       [-39.39173   ],
       [-28.66639   ],
       [-19.05677   ],
       [-22.519173  ],
       [ -9.583383  ],
       [-28.378792  ],
       [-12.848519  ],
       [ -0.3787924 ],
       [-37.20838   ],
       [-25.082405  ],
       [-11.857064  ],
       [-30.85633   ],
       [-25.3451    ],
       [-22.96009   ],
       [-40.559944  ],
       [-21.363655  ],
       [-13.2967615 ],
       [-24.04676   ],
       [ 21.408806  ],
       [  7.7808757 ],
       [-49.574593  ],
       [-33.931282  ],
       [-17.51844   ],
       [-22.236458  ],
       [-29.067268  ],
       [-24.713264  ],
       [ -4.001839  ],
       [-32.37635   ],
       [  4.7593913 ],
       [ -5.817757  ],
       [ -9.315316  ],
       [-41.116096  ],
       [-35.020393  ],
       [ -7.1585774 ],
       [-12.135629  ],
       [-26.35682   ],
       [  3.0855632 ],
       [  3.210075  ],
       [ 21.43029   ],
       [  1.3785318 ],
       [-26.858772  ],
       [-20.662971  ],
       [-23.982552  ],
       [ 13.447135  ],
       [-27.864143  ],
       [  9.596793  ],
       [-39.61634   ],
       [ -9.698617  ],
       [ -1.4339682 ],
       [ 12.832633  ],
       [ -1.5199057 ],
       [-27.367561  ],
       [-25.673225  ],
       [-25.67762   ]], dtype=float32)