In [32]:
pip install pandas

Requirement already satisfied: pandas in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip available: 22.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Pandas is a Python library used for data manipulation, analysis, and handling structured data such as tables, CSV files, and Excel files.

Simple definition:

Pandas = A Python library used to store, organize, clean, and analyze data.

Types of Pandas Data Structures
Type	Definition	Example
Series	One-dimensional (1D) labeled array	Single column
DataFrame	Two-dimensional (2D) labeled table	Rows and columns
1. Series
Stores data in one dimension
Similar to a single column

Example:

import pandas as pd

s = pd.Series([10, 20, 30])

print(s)

Output:

0    10
1    20
2    30
dtype: int64
2. DataFrame
Stores data in rows and columns
Similar to an Excel sheet

Example:

import pandas as pd

data = {
    "Name": ["Ansh", "Rahul"],
    "Age": [22, 24]
}

df = pd.DataFrame(data)

print(df)

Output:

    Name   Age
0   Ansh   22
1  Rahul   24
Summary
Pandas
│
├── Series → 1D
│
└── DataFrame → 2D

Pandas is widely used in Data Analysis, Data Science, Machine Learning, and Data Cleaning.

In [33]:
import pandas as pd
pd.__version__

'3.0.3'

In [34]:
import os

In [35]:
import numpy as np
import pandas as pd

In [36]:
df = pd.read_csv(r"D:\Data Science with AI & ML\PANDAS\Used_Bikes.csv")

In [37]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [38]:
df.head()  # BY default five row

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha

In [39]:
df.head(20)

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
5,Yamaha FZs 150cc,53499.0,Delhi,25000.0,First Owner,6.0,150.0,Yamaha
6,Honda CB Hornet 160R ABS DLX,85000.0,Delhi,8200.0,First Owner,3.0,160.0,Honda
7,Hero Splendor Plus Self Alloy 100cc,45000.0,Delhi,12645.0,First Owner,3.0,100.0,Hero
8,Royal Enfield Thunderbird X 350cc,145000.0,Bangalore,9190.0,First Owner,3.0,350.0,Royal Enfield
9,Royal Enfield Classic Desert Storm 500cc,88000.0,Delhi,19000.0,Second Owner,7.0,500.0,Royal Enfield
10,Yamaha YZF-R15 2.0 150cc,72000.0,Bangalore,20000.0,First Owner,7.0,150.0,Yamaha
11,Yamaha FZ25 250cc,95000.0,Bangalore,9665.0,First Owner,4.0,250.0,Yamaha
12,Bajaj Pulsar NS200,78000.0,Bangalore,9900.0,First Owner,4.0,200.0,Bajaj
13,Bajaj Discover 100M,29499.0,Delhi,20000.0,First Owner,8.0,100.0,Bajaj
14,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj
15,Bajaj Pulsar NS200 ABS,90000.0,Bangalore,11574.0,First Owner,3.0,200.0,Bajaj
16,Bajaj Pulsar RS200 ABS,120000.0,Bangalore,23000.0,First Owner,3.0,200.0,Bajaj
17,Suzuki Gixxer SF 150cc,48000.0,Mumbai,24725.0,First Owner,5.0,150.0,Suzuki
18,Benelli 302R 300CC,240000.0,Mumbai,15025.0,Second Owner,3.0,302.0,Benelli
19,Bajaj Discover 125M,29900.0,Delhi,20000.0,First Owner,7.0,125.0,Bajaj

In [40]:
df.tail() #Niche se row

,bike_name,price,city,kms_driven,owner,age,power,brand
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [41]:
df.tail(20)

,bike_name,price,city,kms_driven,owner,age,power,brand
32628,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj
32629,Bajaj Platina 100cc,23000.0,Lucknow,20000.0,First Owner,6.0,100.0,Bajaj
32630,Suzuki Slingshot Plus 125cc,32000.0,Lucknow,22697.0,First Owner,7.0,125.0,Suzuki
32631,Yamaha SZ-RR 150cc,20000.0,Kanchipuram,52000.0,First Owner,10.0,150.0,Yamaha
32632,Bajaj Avenger Street 220,55005.0,Godhara,6600.0,First Owner,5.0,220.0,Bajaj
32633,Royal Enfield Classic 350cc,87000.0,Gautam Buddha Nagar,16336.0,First Owner,7.0,350.0,Royal Enfield
32634,Royal Enfield Thunderbird 350cc,70000.0,Mumbai,13858.0,Second Owner,11.0,350.0,Royal Enfield
32635,Suzuki Zeus 125cc,35000.0,Ahmedabad,11885.0,First Owner,12.0,125.0,Suzuki
32636,KTM RC 390cc,196700.0,Mumbai,13216.0,First Owner,4.0,390.0,KTM
32637,Bajaj Pulsar 150cc,25000.0,Delhi,32588.0,First Owner,9.0,150.0,Bajaj
32638,Yamaha Fazer 25 250cc,123000.0,Kadapa,14500.0,First Owner,4.0,250.0,Yamaha
32639,Royal Enfield Classic 350cc,95500.0,Delhi,18000.0,First Owner,8.0,350.0,Royal Enfield
32640,Hero Passion Pro 100cc,32000.0,Delhi,12000.0,First Owner,6.0,100.0,Hero
32641,Bajaj Avenger 220cc,41000.0,Delhi,20245.0,Second Owner,11.0,220.0,Bajaj
32642,Hero Passion 100cc,15000.0,Perumbavoor,35000.0,Second Owner,19.0,100.0,Hero
32643,Hero Passion Pro 100cc,39000.0,Delhi,22000.0,First Owner,4.0,100.0,Hero
32644,TVS Apache RTR 180cc,30000.0,Karnal,6639.0,First Owner,9.0,180.0,TVS
32645,Bajaj Avenger Street 220,60000.0,Delhi,20373.0,First Owner,6.0,220.0,Bajaj
32646,Hero Super Splendor 125cc,15600.0,Jaipur,84186.0,First Owner,16.0,125.0,Hero
32647,Bajaj Pulsar 150cc,22000.0,Pune,60857.0,First Owner,13.0,150.0,Bajaj

In [42]:
df.info() # Finding dataset information

<class 'pandas.DataFrame'>
RangeIndex: 32648 entries, 0 to 32647
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   32648 non-null  str
 1   price       32648 non-null  float64
 2   city        32648 non-null  str
 3   kms_driven  32648 non-null  float64
 4   owner       32648 non-null  str
 5   age         32648 non-null  float64
 6   power       32648 non-null  float64
 7   brand       32648 non-null  str
dtypes: float64(4), str(4)
memory usage: 2.0 MB

In [43]:
df.columns

Index(['bike_name', 'price', 'city', 'kms_driven', 'owner', 'age', 'power',
       'brand'],
      dtype='str')

In [44]:
df['brand']

0                  TVS
1        Royal Enfield
2              Triumph
3                  TVS
4               Yamaha
             ...
32643             Hero
32644              TVS
32645            Bajaj
32646             Hero
32647            Bajaj
Name: brand, Length: 32648, dtype: str

In [45]:
df[['brand']]

               brand
0                TVS
1      Royal Enfield
2            Triumph
3                TVS
4             Yamaha
...              ...
32643           Hero
32644            TVS
32645          Bajaj
32646           Hero
32647          Bajaj

[32648 rows x 1 columns]

In [46]:
df[["brand","price"]]

               brand     price
0                TVS   35000.0
1      Royal Enfield  119900.0
2            Triumph  600000.0
3                TVS   65000.0
4             Yamaha   80000.0
...              ...       ...
32643           Hero   39000.0
32644            TVS   30000.0
32645          Bajaj   60000.0
32646           Hero   15600.0
32647          Bajaj   22000.0

[32648 rows x 2 columns]

In [47]:
df['brand'].unique()

<StringArray>
[            'TVS',   'Royal Enfield',         'Triumph',          'Yamaha',
           'Honda',            'Hero',           'Bajaj',          'Suzuki',
         'Benelli',             'KTM',        'Mahindra',        'Kawasaki',
          'Ducati',         'Hyosung', 'Harley-Davidson',            'Jawa',
             'BMW',          'Indian',         'Rajdoot',             'LML',
           'Yezdi',              'MV',           'Ideal']
Length: 23, dtype: str

In [48]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [49]:
df['brand'].nunique()

23

In [50]:
df['brand'].value_counts()

brand
Bajaj              11213
Hero                6368
Royal Enfield       4178
Yamaha              3916
Honda               2108
Suzuki              1464
TVS                 1247
KTM                 1077
Harley-Davidson      737
Kawasaki              79
Hyosung               64
Benelli               56
Mahindra              55
Triumph               26
Ducati                22
BMW                   16
Jawa                  10
MV                     4
Indian                 3
Ideal                  2
Rajdoot                1
LML                    1
Yezdi                  1
Name: count, dtype: int64

In [51]:
df.duplicated().sum()

np.int64(25324)

In [52]:
df.drop_duplicates(inplace=True)

In [53]:
df.duplicated().sum()

np.int64(0)

In [54]:
df.isnull()

      bike_name  price   city  kms_driven  owner    age  power  brand
0         False  False  False       False  False  False  False  False
1         False  False  False       False  False  False  False  False
2         False  False  False       False  False  False  False  False
3         False  False  False       False  False  False  False  False
4         False  False  False       False  False  False  False  False
...         ...    ...    ...         ...    ...    ...    ...    ...
9362      False  False  False       False  False  False  False  False
9369      False  False  False       False  False  False  False  False
9370      False  False  False       False  False  False  False  False
9371      False  False  False       False  False  False  False  False
9372      False  False  False       False  False  False  False  False

[7324 rows x 8 columns]

In [55]:
df.isnull().sum()

bike_name     0
price         0
city          0
kms_driven    0
owner         0
age           0
power         0
brand         0
dtype: int64

In [56]:
df.dropna(inplace=True)

In [57]:
df['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More']
Length: 4, dtype: str

In [58]:
owner_dict = {
  'First Owner', 'Second Owner', 'Third Owner', 'Fourth Owner Or More'
}

In [59]:
df['owner']

0       First Owner
1       First Owner
2       First Owner
3       First Owner
4       First Owner
           ...
9362    First Owner
9369    First Owner
9370    First Owner
9371    First Owner
9372    First Owner
Name: owner, Length: 7324, dtype: str

In [60]:
df['owner']=df['owner'].map(owner_dict)

TypeError: 'set' object is not callable

In [ ]:
df.drop('city',axis=1,inplace=True)

In [ ]:
df

,bike_name,price,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,7127.0,First Owner,5.0,220.0,Bajaj

In [ ]:
df.drop(['bike_name'] , axis=1 , inplace=True)

In [ ]:
df

         price  kms_driven        owner  age  power            brand
0      35000.0     17654.0  First Owner  3.0  110.0              TVS
1     119900.0     11000.0  First Owner  4.0  350.0    Royal Enfield
2     600000.0       110.0  First Owner  8.0  675.0          Triumph
3      65000.0     16329.0  First Owner  4.0  180.0              TVS
4      80000.0     10000.0  First Owner  3.0  150.0           Yamaha
...        ...         ...          ...  ...    ...              ...
9362   25000.0     48587.0  First Owner  8.0  150.0             Hero
9369   35000.0     60000.0  First Owner  9.0  220.0            Bajaj
9370  450000.0      3430.0  First Owner  4.0  750.0  Harley-Davidson
9371  139000.0     21300.0  First Owner  4.0  400.0            Bajaj
9372   80000.0      7127.0  First Owner  5.0  220.0            Bajaj

[7324 rows x 6 columns]

In [61]:
df.info()

<class 'pandas.DataFrame'>
Index: 7324 entries, 0 to 9372
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   bike_name   7324 non-null   str
 1   price       7324 non-null   float64
 2   city        7324 non-null   str
 3   kms_driven  7324 non-null   float64
 4   owner       7324 non-null   str
 5   age         7324 non-null   float64
 6   power       7324 non-null   float64
 7   brand       7324 non-null   str
dtypes: float64(4), str(4)
memory usage: 515.0 KB

In [62]:
obj_val = df.select_dtypes(include='0')

TypeError: data type '' not understood

In [63]:
obj_val

NameError: name 'obj_val' is not defined

In [ ]:
complete_Data = pd.concat([obj_val,num_val],axis =1)

In [64]:
df

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
1,Royal Enfield Classic 350cc,119900.0,Delhi,11000.0,First Owner,4.0,350.0,Royal Enfield
2,Triumph Daytona 675R,600000.0,Delhi,110.0,First Owner,8.0,675.0,Triumph
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
4,Yamaha FZ S V 2.0 150cc-Ltd. Edition,80000.0,Bangalore,10000.0,First Owner,3.0,150.0,Yamaha
...,...,...,...,...,...,...,...,...
9362,Hero Hunk Rear Disc 150cc,25000.0,Delhi,48587.0,First Owner,8.0,150.0,Hero
9369,Bajaj Avenger 220cc,35000.0,Bangalore,60000.0,First Owner,9.0,220.0,Bajaj
9370,Harley-Davidson Street 750 ABS,450000.0,Jodhpur,3430.0,First Owner,4.0,750.0,Harley-Davidson
9371,Bajaj Dominar 400 ABS,139000.0,Hyderabad,21300.0,First Owner,4.0,400.0,Bajaj
9372,Bajaj Avenger Street 220,80000.0,Hyderabad,7127.0,First Owner,5.0,220.0,Bajaj

In [65]:
df[df['brand']=='TVS']

,bike_name,price,city,kms_driven,owner,age,power,brand
0,TVS Star City Plus Dual Tone 110cc,35000.0,Ahmedabad,17654.0,First Owner,3.0,110.0,TVS
3,TVS Apache RTR 180cc,65000.0,Bangalore,16329.0,First Owner,4.0,180.0,TVS
52,TVS Apache RTR 160cc,60000.0,Mumbai,30000.0,First Owner,5.0,160.0,TVS
114,TVS Apache RTR 160 4V Disc,69900.0,Delhi,8700.0,First Owner,3.0,160.0,TVS
130,TVS Phoenix Disc 125cc,21500.0,Barasat,10500.0,First Owner,5.0,125.0,TVS
...,...,...,...,...,...,...,...,...
9247,TVS Apache RTR 160cc Rear Disc,70000.0,Ghaziabad,4116.0,First Owner,3.0,160.0,TVS
9307,TVS Apache RTR 160cc,30000.0,Alibag,30000.0,First Owner,10.0,160.0,TVS
9312,TVS Apache RTR 200 4V FI,65450.0,Delhi,9238.0,First Owner,3.0,200.0,TVS
9320,TVS Apache 150cc,20000.0,Hissar,84916.0,First Owner,14.0,150.0,TVS
9322,TVS Radeon 110cc Drum SBT,58000.0,Delhi,4020.0,First Owner,2.0,110.0,TVS

In [66]:
tvs_brand=df[df['brand']=='TVS']

In [67]:
tvs_brand['owner'].unique()

<StringArray>
['First Owner', 'Second Owner', 'Third Owner']
Length: 3, dtype: str

In [ ]:
tvs_first=tvs_brand[tvs_brand-9['owner']<=2]